apiVersion: v1
entries:
  fleet:
  - apiVersion: v2
    appVersion: v4.54.1
    created: "2024-08-09T10:41:04.450109371Z"
    dependencies:
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.12.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 18.1.6
    description: A Helm chart for Fleet
    digest: e72a1eb6fff3b3a5fdf154f11e8c64a83591b67a2b8273182f5a8c87fdf3fc26
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://pl4nty.github.io/fleet-gh-pages/charts/fleet-v6.2.0.tgz
    version: v6.2.0
  tuf:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-09T10:41:04.450493261Z"
    description: A Helm chart for Kubernetes
    digest: ef38b657fd55a702db21133cc5a030d59e5253cf55ccd869fd3c6e0d2cb2a55f
    name: tuf
    type: application
    urls:
    - https://pl4nty.github.io/fleet-gh-pages/charts/tuf-0.1.0.tgz
    version: 0.1.0
generated: "2024-08-09T10:41:04.440847205Z"
